# Generated by Django 5.1.1 on 2024-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cptdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cptdata',
            name='u',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cptdata',
            name='fs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cptdata',
            name='qc',
            field=models.FloatField(null=True),
        ),
    ]
