# Generated by Django 5.1.1 on 2024-10-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_geol_loca_proj_samp_scpg_scpt_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geol',
            name='FILE_FSET',
            field=models.CharField(blank=True, max_length=255, verbose_name='File Reference'),
        ),
        migrations.AlterField(
            model_name='geol',
            name='GEOL_BGS',
            field=models.CharField(blank=True, max_length=50, verbose_name='BGS Lexicon Code'),
        ),
        migrations.AlterField(
            model_name='geol',
            name='GEOL_FORM',
            field=models.CharField(blank=True, max_length=255, verbose_name='Geological Formation or Stratum Name'),
        ),
        migrations.AlterField(
            model_name='geol',
            name='GEOL_GEO2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Second Geology Code (Soil Unit)'),
        ),
        migrations.AlterField(
            model_name='geol',
            name='GEOL_REM',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='geol',
            name='GEOL_STAT',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stratum Reference Shown on Trial Pit or Traverse Sketch'),
        ),
        migrations.AlterField(
            model_name='geol',
            name='LOCA_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geology_descriptions', to='core.loca', verbose_name='Location Identifier'),
        ),
        migrations.CreateModel(
            name='DREM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DREM_TOP', models.FloatField(verbose_name='Depth to the Top of Stratum (m)')),
                ('DREM_BASE', models.FloatField(verbose_name='Depth to the Base of Description (m)')),
                ('DREM_REM', models.TextField(blank=True, verbose_name='Remarks')),
                ('FILE_FSET', models.CharField(blank=True, max_length=255, verbose_name='File Reference')),
                ('LOCA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depth_remarks', to='core.loca', verbose_name='Location Identifier')),
            ],
        ),
    ]
