# Generated by Django 5.1.1 on 2024-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grag_grat_lnmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grat',
            name='GRAT_PERP',
            field=models.FloatField(help_text='%', verbose_name='Percentage Passing/Finer than GRAT_SIZE (%)'),
        ),
        migrations.AlterField(
            model_name='grat',
            name='GRAT_SIZE',
            field=models.FloatField(help_text='mm', verbose_name='Sieve or Particle Size (mm)'),
        ),
        migrations.AlterField(
            model_name='grat',
            name='SPEC_DPTH',
            field=models.FloatField(help_text='m', verbose_name='Depth to Top of Test Specimen (m)'),
        ),
    ]
