# Generated by Django 5.1.1 on 2024-10-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_drem_id_remove_geol_id_grag_grag_d10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pslt',
            name='PSLG_TESN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ps_logging_test', to='core.pslg', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='scct',
            name='SCCG_TESN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seismic_general', to='core.sccg', verbose_name='Cone ID'),
        ),
        migrations.AlterField(
            model_name='scpt',
            name='SCPG_TESN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cone_id', to='core.scpg', verbose_name='Test Reference or Push Number'),
        ),
    ]
