# Generated by Django 5.1.1 on 2024-10-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_dssg_dssg_bden_remove_dssg_spec_cond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmtd',
            name='PMTG_DPTH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressuremeter_test_depth', to='core.pmtg', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='pmtd',
            name='PMTG_TESN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressuremeter_test_id', to='core.pmtg', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='pmtl',
            name='PMTG_DPTH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressuremeter_loops_depth', to='core.pmtg', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='pmtl',
            name='PMTG_TESN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pressuremeter_loops_id', to='core.pmtg', verbose_name='Test ID'),
        ),
    ]
